(feat) Add theme configuration for frontend and config patient registration

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -7,10 +7,22 @@ RUN mkdir -p /app
 WORKDIR /app
 
 COPY spa-build-config.json .
+COPY config.json .
+COPY /assets /app/assets
 
 ARG CACHE_BUST
 RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} assemble --manifest --mode config --config spa-build-config.json --target ./spa
 RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} build --build-config spa-build-config.json --target ./spa
+
+# Copying required files
+RUN echo "Copying required files ..." && \
+    cp ./assets/login-icon.svg ./spa && \
+    cp ./assets/primary-navigation.png ./spa && \
+    cp ./assets/favicon.ico ./spa && \
+    cp config.json ./spa
+
+# Check build result
+RUN if [ ! -f ./spa/index.html ]; then echo 'Build failed. Please check the logs above for details. This may have happened because of an update to a library that OpenMRS depends on.'; exit 1; fi
 
 FROM nginx:1.23-alpine
 
